version: '2'
services:
  resourcespace:
    image: creecros/resourcespace-docker:latest
    stdin_open: true
    network_mode: bridge
    tty: true
    ports:
      - 4880:80/tcp
    volumes:
      - include:/include
      - filestore:/filestore
  mysql-resourcespace:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: resourcespace
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    stdin_open: true
    network_mode: bridge
    tty: true
    ports:
      - 3306:3306/tcp

volumes:
  filestore:
    driver: local
    driver_opts:
      type: none
      device: /share/CACHEDEV1_DATA/homes/resourcespace/volume/filestore
      o: bind
  include:
    driver: local
    driver_opts:
      type: none
      device: /share/CACHEDEV1_DATA/homes/resourcespace/volume/include
      o: bind
