version: '2'
services:
  resourcespace:
    image: creecros/resourcespace-docker:latest
    stdin_open: true
    tty: true
    ports:
      - ${HTTP_PORT}:80/tcp
    expose:
      - ${HTTP_PORT}
    volumes:
      - include:/include
      - filestore:/filestore
    environment:
      VIRTUAL_HOST: media.fieldcraftstudios.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: media.fieldcraftstudios.com
      LETSENCRYPT_EMAIL: hi@fieldcraft.grwd.uk
  mysql-resourcespace:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: resourcespace
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    stdin_open: true
    tty: true
    ports:
      - 3306:3306/tcp
    volumes:
      - mysql:/var/lib/mysql
volumes:
  filestore:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_FILESTORE}
      o: bind
  include:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_INCLUDE}
      o: bind
  mysql:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_MYSQL}
      o: bind
networks:
  default:
    external:
      name: nginx-proxy
